server:
    port: 8888

spring:
    datasource:
        url: jdbc:oracle:thin:@localhost:1522:xe
        username: bookstore
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        format-sql: true

#logging:
#    level:
#        org:
#            springframework: DEBUG